import type { RuleConfigData } from "@/types";

export const DEFAULT_RULE_CONFIG: RuleConfigData = {
  hardRules: [
    {
      id: "hr_404_410",
      name: "Dead pages (404/410)",
      condition: "statusCode_is_404_or_410",
      recommendation: "CONSIDER_NOINDEX",
      confidence: 0.95,
      reason: "Page returns 404 or 410 status code",
      enabled: true,
    },
    {
      id: "hr_5xx",
      name: "Server error pages",
      condition: "statusCode_is_5xx",
      recommendation: "CONSIDER_NOINDEX",
      confidence: 0.85,
      reason: "Page returns server error status code",
      enabled: true,
    },
    {
      id: "hr_homepage",
      name: "Homepage protection",
      condition: "pageType_is_homepage",
      recommendation: "KEEP_INDEXED",
      confidence: 0.99,
      reason: "Homepage — always keep indexed",
      enabled: true,
    },
    {
      id: "hr_legal",
      name: "Legal page protection",
      condition: "pageType_is_legal",
      recommendation: "KEEP_INDEXED",
      confidence: 0.95,
      reason: "Legal/compliance page — always keep indexed",
      enabled: true,
    },
    {
      id: "hr_canonical_mismatch",
      name: "Canonical points elsewhere",
      condition: "canonical_points_elsewhere",
      recommendation: "MANUAL_REVIEW_REQUIRED",
      confidence: 0.7,
      reason: "Canonical URL points to a different page — needs review",
      enabled: true,
    },
    {
      id: "hr_media_no_value",
      name: "Worthless media/attachment pages",
      condition: "media_attachment_no_value",
      recommendation: "CONSIDER_NOINDEX",
      confidence: 0.9,
      reason: "Media/attachment page with no traffic or backlinks",
      enabled: true,
    },
    {
      id: "hr_empty_tag",
      name: "Empty tag/category pages",
      condition: "empty_tag_category",
      recommendation: "CONSIDER_NOINDEX",
      confidence: 0.85,
      reason: "Tag/category page with minimal content and no traffic",
      enabled: true,
    },
    {
      id: "hr_already_noindexed",
      name: "Already noindexed",
      condition: "meta_robots_noindex",
      recommendation: "CONSIDER_NOINDEX",
      confidence: 0.9,
      reason: "Page already has noindex directive — confirm this is intentional",
      enabled: true,
    },
  ],
  scoreWeights: {
    trafficValue: 0.2,
    businessValue: 0.2,
    contentQuality: 0.15,
    backlinkValue: 0.15,
    internalImportance: 0.1,
    topicalRelevance: 0.1,
    technicalHealth: 0.1,
  },
  scoringThresholds: {
    keepIndexed: 65,
    keepIndexedImprove: 45,
  },
  manualReviewTriggers: [
    {
      id: "mr_backlinks_no_traffic",
      name: "Backlinks but no traffic",
      condition: "has_backlinks_no_traffic",
      reason: "Page has backlinks but no organic traffic — may have link equity worth preserving",
      enabled: true,
    },
    {
      id: "mr_conversions_low_traffic",
      name: "Conversions despite low traffic",
      condition: "has_conversions_low_traffic",
      reason: "Page generates conversions despite low traffic volume",
      enabled: true,
    },
    {
      id: "mr_legal_utility",
      name: "Legal or utility page",
      condition: "is_legal_or_utility",
      reason: "Legal/utility page should not be auto-actioned without review",
      enabled: true,
    },
    {
      id: "mr_low_data",
      name: "Insufficient data",
      condition: "low_data_completeness",
      reason: "Insufficient data to make a confident recommendation",
      enabled: true,
    },
    {
      id: "mr_conflicting_signals",
      name: "Conflicting signals",
      condition: "has_conflicting_signals",
      reason: "Page has conflicting quality signals that need human judgment",
      enabled: true,
    },
    {
      id: "mr_low_confidence",
      name: "Low confidence score",
      condition: "confidence_below_threshold",
      reason: "Classification confidence is too low for auto-action",
      enabled: true,
    },
    {
      id: "mr_near_threshold",
      name: "Score near threshold",
      condition: "score_near_threshold",
      reason: "Score is close to a classification boundary",
      enabled: true,
    },
    {
      id: "mr_location_page",
      name: "Location page",
      condition: "is_location_page",
      reason: "Location pages have strategic local SEO value — review before any action",
      enabled: true,
    },
    {
      id: "mr_has_impressions_no_clicks",
      name: "Impressions but no clicks",
      condition: "has_impressions_no_clicks",
      reason: "Page has search impressions but no clicks — may need improvement, not removal",
      enabled: true,
    },
    {
      id: "mr_service_page_low_traffic",
      name: "Service page with low traffic",
      condition: "service_page_low_traffic",
      reason: "Service/solution page with low traffic — strategically important, needs review",
      enabled: true,
    },
  ],
  pageTypeModifiers: {
    homepage: 50,
    core_service_page: 30,
    service_subpage: 15,
    location_page: 20,
    blog_article: 0,
    evergreen_guide: 10,
    faq_page: 5,
    category_tag_page: -10,
    author_page: -15,
    legal_page: 40,
    utility_page: 10,
    media_attachment: -25,
    old_campaign_page: -20,
    unknown: 0,
  },
};
